# Generated by Django 5.1.2 on 2024-10-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('dt_prev_fim', models.DateField()),
                ('progresso_total', models.DecimalField(decimal_places=2, default=0, help_text='Progresso total da obra em %', max_digits=5)),
                ('gerente', models.ForeignKey(limit_choices_to={'tipo_usuarios': 'gerente'}, on_delete=django.db.models.deletion.CASCADE, related_name='obras_gerenciadas', to='usuarios.perfil')),
                ('mestres', models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuarios': 'mestre'}, related_name='obras_como_mestre', to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço unitário do material', max_digits=10)),
                ('data_compra', models.DateField()),
                ('fornecedor', models.CharField(max_length=100)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='obras.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('progresso', models.DecimalField(decimal_places=2, help_text='Progresso em %', max_digits=5)),
                ('mestre_responsavel', models.ForeignKey(limit_choices_to={'tipo_usuarios': 'mestre'}, on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='usuarios.perfil')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='obras.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=50)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='obras.obra')),
            ],
        ),
    ]
